repos:
    - repo: local
      hooks:
          - id: pytest-before-add
            name: Run pytest before add
            entry: python -m pytest
            language: python
            pass_filenames: false
            stages: [pre-commit]
