repos:
    - repo: local
      hooks:
          - id: pytest-before-push
            name: Run pytest before push
            entry: uv run python -m pytest
            language: system
            pass_filenames: false
            stages: [pre-push]
