name: Publish to PyPI on Version Bump

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    build-test-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install uv
              run: pip install uv

            - name: Install project dependencies with uv
              run: uv pip install --system .[dev]

            - name: Install build tools
              run: pip install build twine pytest

            - name: Clean old dist (optional but recommended)
              run: rm -rf dist/

            - name: Run tests
              run: python -m pytest

            - name: Build distribution
              run: python -m build

            - name: Publish to PyPI
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
              run: twine upload dist/*
